### ISSUE TITLE
Matrix reordering

### ISSUE THREAD

**Issue by zlwu92** [kahypar/mt-kahypar#181]
Hi,

I find this partitioning framework is quite good and wondering if it can be utilized for matrix reordering tasks (adjacency matrix for hypergraph).

**Comment by N-Maas** [comment]
Hi @zlwu92,

could you specify what kind of reordering you want to perform?
You can use a partition of the underlying hypergraph with the km1-metric to get a block structure for a large sparse matrix, i.e., each block of the partition corresponds to a block on the matrix diagonal. The km1 metric then minimizes the number of non-zeros outside of the blocks. This is a typical task for hypergraph partitioning.
If you need another kind of reordering, you should provide more details.

Nikolai

**Comment by zlwu92** [comment]
> The km1 metric then minimizes the number of non-zeros outside of the blocks. This is a typical task for hypergraph partitioning.

I see. Thank you. I'm trying to optimize the cache reuse when using the adjacency matrix of hypergraph to perform a spmm with a dense feature matrix.
In this case, what kind of reordering is suitable?

**Comment by N-Maas** [comment]
Honestly, that sounds like a rather hard problem to model accurately. Cache efficiency will not only depend on the ordering of your matrix, but also on the memory layout of the two matrices and the exact access pattern of the algorithm that is used for multiplication (and even the size of your caches).

I think a block ordering as induced by a partition should generally be advantageous since it improves locality. However, there are probably alternative or additional strategies (reordering within the blocks?) that can achieve even better results. 

Since I don't have much expertise in matrix multiplication, I'm afraid I can't say much more on this topic. I know that cache efficient algorithms are well known for dense-dense matrix multiplication (see e.g. [this](https://en.wikipedia.org/wiki/Cache-oblivious_algorithm) Wikipedia article). I'm sure there is also a lot of research on the sparse-dense case. 

Overall, I think partitioning can help to some degree but to find the best approach you should probably research the existing scientific literature on this subject.

**Comment by zlwu92** [comment]
Thanks.
