### ISSUE TITLE
How to make partition result stable while multi-threading

### ISSUE THREAD

**Issue by jackypiaa** [kahypar/mt-kahypar#189]
Hello,

I used PaToH before and now try to use mt-kahypar for partitioning tasks, and it's working well! However, I have noticed that when running in a multi-threaded setting, the partitioning results seem to vary between runs, even with the same input and settings.

How can I make the partitioning results stable when using multi-threading? Is there any recommended approach to modify source code? or are there specific settings that need to be adjusted to ensure this? 

Thank you for your time and for maintaining this great project. Looking forward to your advice.

Best regards

**Comment by larsgottesbueren** [comment]
Hi,

We offer a deterministic mode, which should be precisely what you're asking for. You can enable it by setting `--preset-type = deterministic` or using the `deterministic_preset.ini` config file in the `configs` folder.

This is not a default setting, as it comes at the cost of some solution quality, because some parallel refinement algorithms (mostly parallel FM) are not amenable to a deterministic implementation. However, we have some experimental code at https://github.com/kahypar/mt-kahypar/tree/rk-determinisitc-coarsening-measurements, which brings the quality up to the same level as the default and quality presets. Feel free to give that branch a try. It should be pretty stable, but just beware, it's still experimental.

The quality roughly corresponds to that of the default preset. If you want the quality of the quality preset, set `--r-flow-algo=deterministic`. If you get non-deterministic results with the deterministic flow-based refinement, try upgrading the submodule, otherwise please report back :).

Hope this helps! 

Cheers,
Lars

**Comment by jackypiaa** [comment]
Hi Lars,

Thanks for your response and the detailed explanation. I have tried using the deterministic mode by setting preset and also the deterministic_preset.ini configuration file . However, I am still encountering vary results between runs. 

I have update both master and rk-determinisitc-coarsening-measurements branch to latest, but the issue persists. Could you provide any further guidance, or is there anything else I might need to configure to ensure consistency? I use C library interface.

Thank you so much!

**Comment by larsgottesbueren** [comment]
That's interesting.... 

1) Does the issue persist when you use the binary?

2) How do you load the hypergraph (The I/O code takes a flag to make it deterministic)? Or do you construct it in memory?

**Comment by jackypiaa** [comment]
I haven't tested the executable file yet. I'll try it later.  I'm sorry that I cannot not provide the hypergraphs. Here is the code snippet.

 mt_kahypar_context_t* context = mt_kahypar_context_new();
  mt_kahypar_load_preset(context, preset);
//mt_kahypar_configure_context_from_file(context, "master/config/deterministic_preset.ini");
//mt_kahypar_configure_context_from_file(context, "rk-determinisitc-coarsening-measurements/config/deterministic_preset.ini");

 
  mt_kahypar_set_partitioning_parameters(context,
    k /* number of blocks */, 0.15 /* imbalance parameter */,
    SOED/* objective function */);

  mt_kahypar_set_context_parameter(context, VERBOSE, "1");

  mt_kahypar_hypergraph_t hypergraph =
    mt_kahypar_creat_hypergraph(preset,c,n,xpins,pins,nwghts,cwghts);//patoh parameter naming

  // Partition Hypergraph
  mt_kahypar_partitioned_hypergraph_t partitioned_hg =
    mt_kahypar_partition(hypergraph, context);

**Comment by jackypiaa** [comment]
Hi Lars, 
I’ve tried binary. It’ works now. I’ll test more large case on it. Thank you so much!

**Comment by larsgottesbueren** [comment]
Thanks! This is great to hear. 

I'll mark this issue as resolved (feel free to reopen if you encounter new problems) and open a new one to investigate and fix the potential non-determinism in the library interface.

**Comment by jackypiaa** [comment]
Hi Lars,

Do you have any suggestions for adjusting options that can increase performance more and still keep results stable? The result of r-flow-algo=deterministic is about 6% worse than preset=quality in my case. 

I’am trying increase number of jet iterations and round , set rebalancer type as quality .

**Comment by larsgottesbueren** [comment]
> Hi Lars,
> 
> Do you have any suggestions for adjusting options that can increase performance more and still keep results stable? The result of r-flow-algo=deterministic is about 6% worse than preset=quality in my case.
> 
> I’am trying increase number of jet iterations and round , set rebalancer type as quality and so on.

6% worse is a lot and feels unexpected. Can you share a bit more information on your configuration, k, epsilon, etc.

**Comment by N-Maas** [comment]
Is the 6% only a single run? On a single instance this might well be the case, but on average over multiple instances and multiple seeds we observed maybe 0.5% worse quality to the non-deterministic configuration.

Generally, to get maximum quality more jet iterations/rounds could help a bit, but more important would be to run the whole partitioner with multiple seeds and use the best observed result (assuming you don't care about running time).

Also note that the rebalancer type will always be `deterministic`, since other rebalancing algorithms don't produce deterministic results.

**Comment by jackypiaa** [comment]
Here are my dataset:

- #HNs:2272358
- #HEs:570568
- #thread:16t
- #k: 1024
- elipson: 0.15
- objective: soed

The SOED are about 74XXX in 10 runs while `preset=quality`, 79191 while `preset=deterministic` `--r-flow-algo=deterministic`.

Thanks for your suggestions and reminders!

**Comment by N-Maas** [comment]
> Here are my dataset:
> 
>     * #HNs:2272358
> 
>     * #HEs:570568
> 
>     * #thread:16t
> 
>     * #k: 1024
> 
>     * elipson: 0.15
> 
>     * objective: soed
> 
> 
> The SOED are about 74XXX in 10 runs while `preset=quality`, 79191 while `preset=deterministic` `--r-flow-algo=deterministic`.
> 
> Thanks for your suggestions and reminders!

Could you try 10 deterministic runs with different seeds? I.e., `--seed=0` for the first run, `--seed=1` for the second run, and so on.

**Comment by jackypiaa** [comment]
seed=0, soed=79161
seed=1, soed=79595
seed=2, soed=
seed=2, soed=
seed=2, soed=
seed=2, soed=

**Comment by jackypiaa** [comment]
seed=0, soed=79161
seed=1, soed=79575
seed=2, soed=79415
seed=3, soed=79236
seed=4, soed=79505
seed=5, soed=79255
seed=6, soed=79001
seed=7, soed=79952
seed=8, soed=79158
seed=9, soed=79853

**Comment by N-Maas** [comment]
> seed=0, soed=79161
> seed=1, soed=79575
> seed=2, soed=79415
> seed=3, soed=79236
> seed=4, soed=79505
> seed=5, soed=79255
> seed=6, soed=79001
> seed=7, soed=79952
> seed=8, soed=79158
> seed=9, soed=79853

It seems indeed the deterministic config performs consistently worse on your instance. Though I'm afraid without access to the data we can't do much about it.

You could try to find out which component causes the quality decrease by starting with the non-deterministic version and replacing coarsening, FM/Jet and flows one by one with the deterministic counterpart. Of course this wouldn't necessarily allow to improve it.
